# Generated by Django 4.0.4 on 2022-06-22 12:21

from django.db import migrations, models
import import_movies.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='posters/', validators=[import_movies.utils.validate_file_extension])),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
