# Generated by Django 4.0.4 on 2022-06-24 08:02

from django.db import migrations, models
import import_movies.utils


class Migration(migrations.Migration):

    dependencies = [
        ('import_movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importmoviesmodel',
            name='file',
            field=models.FileField(upload_to='imported_zips/', validators=[import_movies.utils.validate_file_extension]),
        ),
    ]
