# Generated by Django 4.0.4 on 2022-06-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('cinema', models.CharField(max_length=40)),
            ],
        ),
    ]
