# Generated by Django 4.0.4 on 2022-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('description', models.TextField()),
                ('imdb_link', models.CharField(max_length=100)),
                ('imdb_id', models.CharField(max_length=100)),
                ('trailer_url', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('available_from', models.DateField()),
            ],
            options={
                'ordering': ('available_from',),
            },
        ),
    ]
