# Generated by Django 4.0.4 on 2022-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_cinema_hall_hall_cinema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name',
            field=models.CharField(default='Hall', max_length=50),
        ),
    ]
