# Generated by Django 4.0.4 on 2022-06-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_hall_description_hall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.hall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='name',
            field=models.CharField(choices=[('A1', 1), ('B1', 2)], default=1, max_length=3),
        ),
    ]
