# Generated by Django 4.0.4 on 2022-06-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_seat_hall_seat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='rows',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='hall',
            name='seats_per_row',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(default='A1', max_length=4),
        ),
    ]
