# Generated by Django 4.0.4 on 2022-06-06 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0006_hall_rows_hall_seats_per_row_seat_is_reserved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('assigned_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reserved_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.playingtime')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat')),
            ],
        ),
    ]
