# Generated by Django 4.0.4 on 2022-06-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_playingtime_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_reserved',
        ),
    ]
