# Generated by Django 4.0.4 on 2022-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_seat_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cinema_logo/'),
        ),
    ]
