# Generated by Django 4.0.4 on 2022-06-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_reservation_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cinema.playingtime'),
        ),
    ]
