# Generated by Django 4.0.4 on 2022-06-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_create_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
