# Generated by Django 4.0.4 on 2022-06-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0015_alter_playingtime_assigned_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halls",
                to="cinema.cinema",
            ),
        ),
    ]
