
on:
  push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
        pr_label: "automerge"
        pr_reviewer: "drejleeo"
